
-- Queries Table
-- This table stores submissions from the contact form.

CREATE TABLE queries (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  name TEXT,
  email TEXT,
  message TEXT,
  status TEXT DEFAULT 'new',
  notes TEXT
);

-- Enable Row Level Security (RLS)
ALTER TABLE queries ENABLE ROW LEVEL SECURITY;

-- Policies for 'queries' table
-- 1. No public access to any rows.
-- This setup assumes that you will only access this data via the Supabase dashboard
-- or using your secret 'service_role' key from the server, which bypasses RLS.
-- This is the most secure default for sensitive client data.

-- If you needed to allow logged-in users to see their own queries in the future,
-- you would add a policy like this:
-- CREATE POLICY "Allow individual read access" ON queries FOR SELECT
-- USING (auth.uid() = user_id);
